application: jasdeep-hundal
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /static
  static_dir: static
- url: /(.*)/
  static_files: \1/index.html
  upload: .*/index\.html
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
